name: build_mac
on: push
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: env | sort
      - name: Update Homebrew
        run: |
          brew update --preinstall
      - name: Install java
        run: |
          which java
      - name: install deps
        run: |
          npm install
      - name: build migrate
        run: |
          npm run migrate
      - name: build release
        run: |
          npm run release
