name: build_mac
on: push
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: init project
        uses: ./.github/actions/init
      - name: make build
        run: |
          make build-all
      - name: git diff
        run: |
          git add .
          DIFF=`git diff --cached --name-only | grep -e src.md5 | wc -l`
          if [ $DIFF -gt 0 ]; then
            git diff --cached -- src.md5
            echo "need make build-all and push diff"
            exit 1
          fi
