name: build_mac
on: push
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: init project
        uses: ./.github/actions/init
      - name: build openapi
        run: |
          npm run openapi
          npm run start_openapi
      - name: build migrate
        run: |
          npm run migrate
      - name: build release
        run: |
          npm run release
      - name: check git diff
        run: |
          git add .
          DIFF=`git --no-pager diff --cached | wc -l`
          git --no-pager diff --name-only --cached
          if [ $DIFF -gt 0 ]; then
            echo "need build and push"
            exit 1
          fi
